### ISSUE TITLE
Really use artifacts expiration setting

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#1035]
Currently, the artifacts expiration setting is saved in the task, together with the upload link. But in the worker, the expiration setting is never used by the task worker which should pass this information to the uploader to set proper retention rule.

**Comment by elfkuzco** [comment]
I think this might have to do with python-storagelib instead. Ran with my S3 bucket and got this:
```
[2025-10-23 16:01:11,294: INFO] Setting autodelete to 2025-10-24 16:02:11.294815
[2025-10-23 16:01:12,624: ERROR] Failed to set autodelete: 400 Client Error: Bad Request for url: https://s3.us-west-1.wasabisys.com/org-kiwix-dev-uche/e14e8d3a-5b33-4bb0-a8cf-882b8df355b4_mwoffliner.log?compliance
[2025-10-23 16:01:12,625: ERROR] 400 Client Error: Bad Request for url: https://s3.us-west-1.wasabisys.com/org-kiwix-dev-uche/e14e8d3a-5b33-4bb0-a8cf-882b8df355b4_mwoffliner.log?compliance
Traceback (most recent call last):
  File "/usr/local/bin/uploader", line 399, in s3_upload_file
    s3_storage.set_object_autodelete_on(key=key, on=expire_on)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kiwixstorage/__init__.py", line 560, in set_object_autodelete_on
    return self.set_wasabi_compliance(compliance, key=key, bucket_name=bucket_name)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kiwixstorage/__init__.py", line 662, in set_wasabi_compliance
    req.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://s3.us-west-1.wasabisys.com/org-kiwix-dev-uche/e14e8d3a-5b33-4bb0-a8cf-882b8df355b4_mwoffliner.log?compliance
[2025-10-23 16:01:12,632: INFO] removing source file…
[2025-10-23 16:01:12,633: INFO] :: success.
[2025-10-23 16:01:12,633: INFO] [stats] uploaded 4.88 KiB in 5.15 seconds (970.1977397014821 bytes/s)
```

Perhaps, the buckets aren't configured properly?

**Comment by benoit74** [comment]
This was for a log file, not for an artifact, I suspect logic might be slightly different. If I remember well, I saw in the codebase that the expiration setting for artifacts was not passed to the uploader.

The problem you have with this error you saw is that your `org-kiwix-dev-uche` bucket does not have compliance turned on, so you cannot set an autodelete rule on objects, this is expected behavior (hence the fact that uploader ignores it silently).

Could you test with an artifact as well (you just need to configure artifacts to `**/*.*` in a small task, everything including the ZIM will be uploaded to artifacts) ? But indeed maybe it is only the bucket which was badly configured.

I've created a new `org-kiwix-dev-expiring` bucket which has compliance configured just like on all other production buckets which should expire objects, i.e. with compliance turned on and expiration set to 1 day (meaning unless specified differently by the uploader, objects will be deleted after 1 day). This is going to be a shared bucket across all devs, but I do not expect to have conflicts + objects will anyway expire often. Please confirm you have access to this bucket and the uploader correctly set autodelete without issue.

Thank you very much for brigging all this underserved topics on the table, glad we will have better situation around all this soon.
