### ISSUE TITLE
UserCreateSchema does not require all properties while they seem required

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#1058]
- Location: API 

## Problem

When someone was creating a user, we've got following exception:

```
1733292679921	ERROR:uwsgi_file__app_main:Exception on /v1/users/ [POST]
1733292679921	Traceback (most recent call last):
1733292679921	  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
1733292679921	    response = self.full_dispatch_request()
1733292679921	  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
1733292679921	    rv = self.handle_user_exception(e)
1733292679921	  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
1733292679921	    return cors_after_request(app.make_response(f(*args, **kwargs)))
1733292679921	  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
1733292679921	    rv = self.dispatch_request()
1733292679921	  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
1733292679921	    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
1733292679921	  File "/app/./routes/base.py", line 20, in __call__
1733292679921	    return handler(*args, **kwargs)
1733292679921	  File "/app/./routes/__init__.py", line 35, in wrapper
1733292679921	    return f(*args, **kwargs)
1733292679921	  File "/app/./db/__init__.py", line 50, in inner
1733292679921	    return func(*args, **kwargs)
1733292679921	  File "/app/./routes/__init__.py", line 53, in wrapper
1733292679921	    return f(*args, **kwargs)
1733292679921	  File "/app/./routes/users/user.py", line 62, in post
1733292679921	    email=request_json["email"],
1733292679921	KeyError: 'email'
1733292679922	[pid: 30|app: 0|req: 8631/19159] 100.64.6.69 () {68 vars in 1813 bytes} [Wed Dec  4 06:11:19 2024] POST /v1/users/ => generated 265 bytes in 9 msecs (HTTP/1.1 500) 4 headers in 168 bytes (1 switches on core 0)
1733292679923	100.64.6.69 - - [04/Dec/2024:06:11:19 +0000] "POST /v1/users/ HTTP/1.1" 500 265 "https://farm.openzim.org/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "185.72.67.134"

```

## Reproducing steps

Create a user without any email

## Analysis

Create user endpoint is at https://github.com/openzim/zimfarm/blob/6b4dc7a81bb24b666fa8f89d17b0c23d56fa12de/dispatcher/backend/src/routes/users/user.py#L51-L76

It relies on `UserCreateSchema` at https://github.com/openzim/zimfarm/blob/6b4dc7a81bb24b666fa8f89d17b0c23d56fa12de/dispatcher/backend/src/common/schemas/parameters.py#L146-L150

This schema does not require all fields, while it probably should

**Comment by elfkuzco** [comment]
@benoit74 , can you take a look at this? Seems to have been fixed as a consequence of the `zimfarm-upgrade`

**Comment by benoit74** [comment]
I confirm it is solved, it now causes a 422 with proper error details:

```
> curl -X 'POST' \
  'http://localhost:8000/v2/users' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer xxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "bob",
  "role": "admin"
}'
{"success":false,"message":"Input values failed constraints validation","errors":{"password":"Field required","email":"Field required"}}
```

This will be deployed in prod with `zimfarm-upgrade` branch.
