### ISSUE TITLE
Crashes by running kelson_worker

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#125]
```
$ docker logs -f zimfarm_worker
[2019-02-02 14:27:24,214: INFO] Starting Zimfarm Worker...
[2019-02-02 14:27:24,621: INFO] ENV USERNAME -- kelson
[2019-02-02 14:27:24,623: INFO] ENV DISPATCHER_HOST -- farm.openzim.org
[2019-02-02 14:27:24,624: INFO] ENV RABBIT_PORT -- 5671
[2019-02-02 14:27:24,626: INFO] ENV WAREHOUSE_HOST -- warehouse.farm.openzim.org
[2019-02-02 14:27:24,627: INFO] ENV WAREHOUSE_PORT -- 1522
[2019-02-02 14:27:24,629: INFO] ENV WORKING_DIR -- /data/zimfarm/tmp
[2019-02-02 14:27:24,631: INFO] ENV NODE_NAME -- kelson_worker
[2019-02-02 14:27:24,632: INFO] ENV QUEUES -- small
[2019-02-02 14:27:26,111: ERROR] SFTP auth check failed -- please double check your username and private key.
[2019-02-02 14:46:04,366: INFO] Starting Zimfarm Worker...
[2019-02-02 14:46:04,774: INFO] ENV USERNAME -- kelson
[2019-02-02 14:46:04,775: INFO] ENV DISPATCHER_HOST -- farm.openzim.org
[2019-02-02 14:46:04,776: INFO] ENV RABBIT_PORT -- 5671
[2019-02-02 14:46:04,777: INFO] ENV WAREHOUSE_HOST -- warehouse.farm.openzim.org
[2019-02-02 14:46:04,777: INFO] ENV WAREHOUSE_PORT -- 1522
[2019-02-02 14:46:04,778: INFO] ENV WORKING_DIR -- /data/zimfarm/tmp
[2019-02-02 14:46:04,779: INFO] ENV NODE_NAME -- kelson_worker
[2019-02-02 14:46:04,780: INFO] ENV QUEUES -- small
[2019-02-02 14:46:05,334: INFO] SFTP auth check success.
/usr/local/lib/python3.6/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2019-02-02 14:46:06,434: INFO/MainProcess] Connected to amqps://kelson:**@farm.openzim.org:5671/zimfarm
[2019-02-02 14:46:06,743: INFO/MainProcess] mingle: searching for neighbors
[2019-02-02 14:46:08,360: INFO/MainProcess] mingle: all alone
[2019-02-02 14:46:08,994: INFO/MainProcess] kelson@kelson_worker ready.
[2019-02-02 14:46:09,000: INFO/MainProcess] Received task: offliner.mwoffliner[5c5129548c127b00217cb4af]
[2019-02-02 14:46:09,010: INFO/MainProcess] Received task: offliner.mwoffliner[5c5129548c127b00217cb4b2]
[2019-02-02 14:46:09,158: INFO/MainProcess] Received task: offliner.mwoffliner[5c5129558c127b00217cb4b5]
[2019-02-02 14:46:09,169: INFO/MainProcess] Received task: offliner.mwoffliner[5c5129558c127b00217cb4b8]
/usr/local/lib/python3.6/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2019-02-02 14:46:25,858: ERROR/ForkPoolWorker-2] offliner.mwoffliner[5c5129548c127b00217cb4af]: task failed
[2019-02-02 14:46:25,861: ERROR/ForkPoolWorker-2] Task offliner.mwoffliner[5c5129548c127b00217cb4af] raised unexpected: APIError(HTTPError('409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/create?name=zimfarm_redis',),)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/create?name=zimfarm_redis

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/tasks/mwoffliner.py", line 41, in run
    run_redis.execute()
  File "/usr/src/app/operations/run_redis.py", line 31, in execute
    self.docker.containers.run('redis', detach=True, name=self.container_name)
  File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 785, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 843, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 427, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 438, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/zimfarm_redis" is already in use by container "e85ce7f7fe3d000f4824879405268e63c846af7d47a325e4655f17659d22e926". You have to remove (or rename) that container to be able to reuse that name.")
[2019-02-02 14:46:25,935: INFO/MainProcess] Received task: offliner.mwoffliner[5c5129558c127b00217cb4bb]
[2019-02-02 14:46:27,667: ERROR/ForkPoolWorker-2] offliner.mwoffliner[5c5129558c127b00217cb4b5]: task failed
[2019-02-02 14:46:27,675: ERROR/ForkPoolWorker-2] Task offliner.mwoffliner[5c5129558c127b00217cb4b5] raised unexpected: APIError(HTTPError('409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/create?name=zimfarm_redis',),)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/create?name=zimfarm_redis

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/tasks/mwoffliner.py", line 41, in run
    run_redis.execute()
  File "/usr/src/app/operations/run_redis.py", line 31, in execute
    self.docker.containers.run('redis', detach=True, name=self.container_name)
  File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 785, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 843, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 427, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 438, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/zimfarm_redis" is already in use by container "e85ce7f7fe3d000f4824879405268e63c846af7d47a325e4655f17659d22e926". You have to remove (or rename) that container to be able to reuse that name.")
[2019-02-02 14:46:27,748: INFO/MainProcess] Received task: offliner.mwoffliner[5c5129558c127b00217cb4be]
/usr/local/lib/python3.6/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
```

**Comment by automactic** [comment]
What has caused the crash has been fixed
