### ISSUE TITLE
Worker can't access docker anymore

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#221]
[//]: # (Pick appropriate classifiers)
- Location: __Worker__
- Task ID: 5ced6785f8c0af00205cea1d

## Problem

Worker is unable to start any docker container as it doesn't have enough permission on the docker socket.

It seems that it as been introduced in [6b3b9fe4e](https://github.com/openzim/zimfarm/commit/6b3b9fe4e68ee474a85a9d8a72e33097c9954c9b#diff-3608a1407b8b3aeae1b63438eeb7f3dbR10) and [6b3b9fe4e](https://github.com/openzim/zimfarm/commit/6b3b9fe4e68ee474a85a9d8a72e33097c9954c9b#diff-dae9b3f2c594579d44d0eb1c590d39aaR68) when switching to running celery as a regular user.

## Reproducing steps

Start any task and observe the following output:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/tasks/mwoffliner.py", line 40, in run
    with RunRedis(docker_client=docker.from_env(), task_id=self.task_id) as redis_container:
  File "/usr/src/app/operations/run_redis.py", line 34, in __enter__
    return self.execute()
  File "/usr/src/app/operations/run_redis.py", line 26, in execute
    self._remove_existing()
  File "/usr/src/app/operations/run_redis.py", line 42, in _remove_existing
    containers = self.docker.containers.list(all=True, filters={'name': self._container_name})
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 918, in list
    since=since)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 208, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 399, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 339, in on_error
    task, request, eager=eager, call_errbacks=call_errbacks,
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 172, in handle_error_state
    call_errbacks=call_errbacks)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 220, in handle_failure
    task.on_failure(exc, req.id, req.args, req.kwargs, einfo)
  File "/usr/src/app/tasks/base.py", line 46, in on_failure
    self.clean_up()
  File "/usr/src/app/tasks/base.py", line 28, in clean_up
    shutil.rmtree(working_dir)
  File "/usr/local/lib/python3.7/shutil.py", line 482, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/local/lib/python3.7/shutil.py", line 480, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/zim_files/5ced6785f8c0af00205cea1d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 556, in _fast_trace_task
    uuid, args, kwargs, request,
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 499, in trace_task
    I, _, _, _ = on_error(task_request, exc, uuid)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 339, in on_error
    task, request, eager=eager, call_errbacks=call_errbacks,
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 172, in handle_error_state
    call_errbacks=call_errbacks)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 220, in handle_failure
    task.on_failure(exc, req.id, req.args, req.kwargs, einfo)
  File "/usr/src/app/tasks/base.py", line 46, in on_failure
    self.clean_up()
  File "/usr/src/app/tasks/base.py", line 27, in clean_up
    working_dir = Path(Settings.working_dir_container).joinpath(self.task_id)
  File "/usr/local/lib/python3.7/pathlib.py", line 898, in joinpath
    return self._make_child(args)
  File "/usr/local/lib/python3.7/pathlib.py", line 688, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.7/pathlib.py", line 642, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by rgaudin** [comment]
Solutions:

### A. remove `--uid` and run celery as root as it was.

### B. on start-up

* find the `gid` of the docker socket on the host
`SOCK_DOCKER_GID=(ls -ng /var/run/docker.sock | cut -f3 -d' ')`
* change `docker` group `gid`
`groupmod -g ${SOCK_DOCKER_GID} -o docker` on `docker` group in the container
* add group to `celery_runner`
`usermod -aG docker celery_runner`
* finally run the actual entrypoint as `celery_runner`.
Good sample at https://github.com/sudo-bmitch/jenkins-docker/blob/master/entrypoint.sh

@kelson42 @automactic what do you think?

**Comment by automactic** [comment]
Hmm, totally cannot see the same thing appear on my machine...
Maybe that is just because I am in the docker group?

**Comment by rgaudin** [comment]
If, by chance, the docker `gid` on your computer matches the one on the container (it's the first one created here), then it magically works.
