### ISSUE TITLE
WPEN movie selection can not be done with 1.9.3

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#260]
@Joe We can discuss this, but the problem for now, it that mwoffliner seems to crash, see https://farm.openzim.org/tasks/5d02afb98b9bc40020fc534e

Command

```
mwoffliner --adminEmail="contact@kiwix.org" --format="nopic" --format="novid" --mwUrl="https://en.wikipedia.org/" --customZimFavicon="https://upload.wikimedia.org/wikipedia/commons/8/84/Biofilm.png" --customZimTitle="Movies by Wikipedia" --customZimDescription="A selection of Wikipedia articles on movies" --articleList="http://download.kiwix.org/wp1/enwiki/customs/movies" --useCache --redis="redis://redis" --outputDirectory="/output"
```

Standard Error
```
[error] [2019-06-13T20:33:06.278Z] Error retrieving article: HTTP 404
[error] [2019-06-13T21:09:39.723Z] Error retrieving article: HTTP 404
[error] [2019-06-13T23:54:11.999Z] Error retrieving article: HTTP 404
[error] [2019-06-14T00:43:50.921Z] Error retrieving article: HTTP 404
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to redis:6379 failed - write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)
Emitted 'error' event at:
    at RedisClient.on_error (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:613:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)
```

**Comment by kelson42** [comment]
I have moved this issue to zimfarm repo, as it seems quite clear this is related to Docker/Zimfarm.

**Comment by rgaudin** [comment]
> @rgaudin I don't see anything obvious - no error happening :(

Well we can see that redis was not terminated properly, as it is on successful runs. It lacks the following:

```
1:signal-handler (1562151022) Received SIGTERM scheduling shutdown...
1:M 03 Jul 2019 10:50:22.192 # User requested shutdown...
1:M 03 Jul 2019 10:50:22.192 * Removing the unix socket file.
1:M 03 Jul 2019 10:50:22.192 # Redis is now ready to exit, bye bye...
```

Maybe it crashes completely or gets killed by the system?

@kelson42 have you tried to run it locally (via docker though)?

@ISNIT0 are you testing from the codebase or via the mwoffliner docker image? If it succeeds, please share details on redis version/command line and machine specs.

**Comment by automactic** [comment]
Could it be related to the logic that kills stuck containers?

**Comment by kelson42** [comment]
@automactic Might be.. we really need to be informed about that scenario if this happens, I have open a ticket just for that here #261.

**Comment by kelson42** [comment]
@rgaudin Why I read `Running mode=standalone, port=6379` ? I thought the server listen on a socket!

**Comment by rgaudin** [comment]
> @rgaudin Why I read `Running mode=standalone, port=6379` ? I thought the server listen on a socket!

It does, look at the last line. We are connecting to redis via the socket, the TCP connection is idle. We can disable it as well (setting `port 0`).

When container (mwoffliner) is `kill()`ed because it's stuck, redis is stoppped properly. Here's a trace of a killed run:

```
1:C 04 Jul 2019 13:22:58.639 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 04 Jul 2019 13:22:58.639 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 04 Jul 2019 13:22:58.639 # Configuration loaded
1:M 04 Jul 2019 13:22:58.646 * Running mode=standalone, port=0.
1:M 04 Jul 2019 13:22:58.646 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 04 Jul 2019 13:22:58.646 # Server initialized
1:M 04 Jul 2019 13:22:58.646 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 04 Jul 2019 13:22:58.646 * The server is now ready to accept connections at /tmp/sockets/redis_5d1dfda693b5e1fca9d038ff.sock
1:signal-handler (1562246596) Received SIGTERM scheduling shutdown...
1:M 04 Jul 2019 13:23:16.242 # User requested shutdown...
1:M 04 Jul 2019 13:23:16.242 * Removing the unix socket file.
1:M 04 Jul 2019 13:23:16.248 # Redis is now ready to exit, bye bye...
```

So I don't think the container was neither stuck nor killed.

**Comment by kelson42** [comment]
We are not sure to fully understand why, but with MWoffliner 1.9.4, we have achieved to have a successful run. So I guess we can close that ticket for now. That said I wouldn't be surprised if the bug reappears.
