### ISSUE TITLE
We need a trace (log) if worker is killing scraper container (because of inactivity)

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#261]
It looks like for now, we have no way to know that. See:
https://github.com/openzim/zimfarm/issues/260#issuecomment-508294636

To efficiently analyse failing scrapings, we need this information.

**Comment by rgaudin** [comment]
We have that information on the worker log but it is not transmitted to the zimfarm:

```
[2019-07-04 13:22:47,178: INFO/MainProcess] Received task: offliner.mwoffliner[5d1dfda693b5e1fca9d038ff]
/usr/local/lib/python3.7/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2019-07-04 13:23:02,535: INFO/ForkPoolWorker-1] offliner.mwoffliner[5d1dfda693b5e1fca9d038ff]: Running DNSCache at 172.17.0.4
[2019-07-04 13:23:02,550: INFO/ForkPoolWorker-1] offliner.mwoffliner[5d1dfda693b5e1fca9d038ff]: Running MWOffliner, mwUrl: https://fr.wikipedia.org/
[2019-07-04 13:23:07,167: INFO/ForkPoolWorker-1] offliner.mwoffliner[5d1dfda693b5e1fca9d038ff]: Detected container stuck. Terminating...
[2019-07-04 13:23:07,847: INFO/ForkPoolWorker-1] Uploading files, mwoffliner_5d1dfda693b5e1fca9d038ff.log.xz - 32
[2019-07-04 13:23:16,160: INFO/ForkPoolWorker-1] offliner.mwoffliner[5d1dfda693b5e1fca9d038ff]: MWOffliner finished, mwUrl: https://fr.wikipedia.org/, exit code: 137
[2019-07-04 13:23:16,947: INFO/ForkPoolWorker-1] Uploading files, redis_5d1dfda693b5e1fca9d038ff.log.xz - 756
[2019-07-04 13:23:18,463: ERROR/ForkPoolWorker-1] Task offliner.mwoffliner[5d1dfda693b5e1fca9d038ff] raised unexpected: Exception('Command /bin/bash -c "sleep 600" in image openzim/mwoffliner:1.9.3 returned with non-zero exit code 137.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/tasks/mwoffliner.py", line 56, in run
    raise Exception(str(result))
Exception: Command /bin/bash -c "sleep 600" in image openzim/mwoffliner:1.9.3 returned with non-zero exit code 137.
```
