### ISSUE TITLE
Timeout on docker socket read

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#378]
[A task](https://farm.openzim.org/pipeline/5e1857d94b418fd0ad50510f/debug) failed as its worker timed out reading the docker API socket.

This is very unlikely and not something we have control over. We should give it a though and decide whether it's a failing case that should fail or if we want to do something about it.

At least we should understand under which circumstance this might happen.

```
Traceback (most recent call last):
  File "/usr/local/bin/task-worker", line 60, in main
    sys.exit(worker.run())
  File "/usr/src/app/task/worker.py", line 420, in run
    self.upload_log()
  File "/usr/src/app/task/worker.py", line 357, in upload_log
    self.log_uploader = start_uploader(
  File "/usr/src/app/common/docker.py", line 410, in start_uploader
    return run_container(
  File "/usr/src/app/common/docker.py", line 78, in run_container
    return retried_docker_call(docker_client.containers.run, *args, **kwargs)
  File "/usr/src/app/common/docker.py", line 40, in retried_docker_call
    return docker_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 809, in run
    container.start()
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 400, in start
    return self.client.api.start(self.id, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 1094, in start
    res = self._post(url)
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 226, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

**Comment by rgaudin** [comment]
We might also instanciate our docker client with a higher `timeout`, default one being `60s`.

**Comment by kelson42** [comment]
@rgaudin Valid solution to me, I see no problem to extend it to 360 seconds for example
