### ISSUE TITLE
Race condition in log container disposal

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#384]
```
docker.errors.APIError: 409 Client Error: Conflict ("removal of container 08d3e_logup_35e8b72192a168a59e36abd643fce4fc2271a953f7c7ecc29b220b75572f749b-json.log is already in progress")
```

Task: [#08d3e](https://farm.openzim.org/pipeline/5e1d422688324be2e9508d3e/debug) `wikipedia_ru_all` on `mwoffliner4`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/08d3e_logup_35e8b72192a168a59e36abd643fce4fc2271a953f7c7ecc29b220b75572f749b-json.log?v=False&link=False&force=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/task-worker", line 60, in main
    sys.exit(worker.run())
  File "/usr/src/app/task/worker.py", line 420, in run
    self.upload_log()
  File "/usr/src/app/task/worker.py", line 352, in upload_log
    remove_container(self.docker, self.log_uploader.name)
  File "/usr/src/app/common/docker.py", line 96, in remove_container
    return retried_docker_call(docker_client.api.remove_container, *args, **kwargs)
  File "/usr/src/app/common/docker.py", line 48, in retried_docker_call
    raise exc
  File "/usr/src/app/common/docker.py", line 40, in retried_docker_call
    return docker_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 996, in remove_container
    self._raise_for_status(res)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("removal of container 08d3e_logup_35e8b72192a168a59e36abd643fce4fc2271a953f7c7ecc29b220b75572f749b-json.log is already in progress")
```

We should not arrive at this line of code if the container is not already removed. Maybe docker's status is not correct and we should had an extra step to actually ensure it has been fully removed before proceeding…

**Comment by kelson42** [comment]
@rgaudin I saw that this morning for WPRU, I have rescheduled it, just hope this does not happen too often.

**Comment by rgaudin** [comment]
Yes, well given the log uploader is started/removed all the time, the chance of this happening is not negligible and this can happen at any moment. Here it happened during the creation of the second zim… so big waste of time.

we can probably prevent it by just waiting a couple seconds before restarting it but I'd like to know why docker is telling us it's been removed why it's not.

**Comment by kelson42** [comment]
https://farm.openzim.org/pipeline/5e1dd7d7637255cf61da6681/debug

**Comment by rgaudin** [comment]
@kelson42 this should be safer ; although, while frequent, this problem is not reproducible on-demand and we're dealing with an unexpected scenario (`status=removed` yet creating with same name raises conflict)… so we'll have to test it live.

I'm closing this for now ; please reopen if the problem arise again. we should have a little more information with this code but if this is not enough we'll probably go down the workaround road ( use unique names for container)

So let's watch tasks started after Feb 17 18:30 UTC.

**Comment by rgaudin** [comment]
reopening as we got a Conflict on the prune step

```
docker.errors.APIError: 409 Client Error: Conflict ("a prune operation is already running")
```

https://farm.openzim.org/pipeline/5e45f173f56bd3187425d807/debug

As we can't really know if such an operation is in progress and catching this Conflict would not be much helpful, we will:

* switch to using unique names for log uploads
* attempt to remove container and not crash on Conflict (print the error only)
* leave it for the crontask `zimfarm prune` to clean it up eventually

**Comment by rgaudin** [comment]
This new PR should protect us from this:
* we now use uniq names so no more conflict on uploader container creation
* we may still encounter conflict on removal of those container
* but we would just print the error and not fail
* including for prune that we kept.

let's watch this for tasks started after after 13:45 UTC today

**Comment by rgaudin** [comment]
Not the same bug, but related to the fix

https://farm.openzim.org/pipeline/5e4b4564f999d553387477a8/debug

Already happened 3 times.

```
[2020-02-20 05:41:57,033: INFO] starting zimfarm task-worker for 5e4b4564f999d553387477a8.
[2020-02-20 05:41:57,033: INFO] configuration:
	username=wmf-worker
	webapi_uri=https://api.farm.openzim.org/v1
	workdir=/data
	task_id=5e4b4564f999d553387477a8
[2020-02-20 05:41:57,033: INFO] testing workdir at /data…
[2020-02-20 05:41:57,034: INFO] 	workdir is available and writable
[2020-02-20 05:41:57,034: INFO] testing private key at /etc/ssh/keys/zimfarm…
[2020-02-20 05:41:57,034: INFO] 	private key is available and readable
[2020-02-20 05:41:57,034: INFO] testing authentication with https://api.farm.openzim.org/v1…
[2020-02-20 05:41:57,935: INFO] 	authentication successful
[2020-02-20 05:41:57,936: INFO] testing docker API on /var/run/docker.sock…
[2020-02-20 05:41:57,988: INFO] 	docker API access successful
[2020-02-20 05:41:57,989: INFO] Container resources:
	RAM  (total): 8 EiB
	RAM  (avail): 8 EiB
	CPUs: 8
	Disk: 204.79 GiB
[2020-02-20 05:41:57,989: INFO] registering exit signals
[2020-02-20 05:41:57,989: INFO] Fetching task details for 5e4b4564f999d553387477a8
[2020-02-20 05:41:58,469: INFO] Updating task-status=started
[2020-02-20 05:41:59,357: INFO] Setting-up workdir
[2020-02-20 05:41:59,362: INFO] Starting DNS cache
[2020-02-20 05:42:00,352: DEBUG] DNS Cache started using IPs: ['172.17.0.9']
[2020-02-20 05:42:00,352: INFO] Starting scraper. Expects files at: /srv/zimfarm/data/5e4b4564f999d553387477a8 
[2020-02-20 05:42:00,354: DEBUG] pulling image openzim/mwoffliner:dev
[2020-02-20 05:42:01,118: INFO] Updating task-status=scraper_started
[2020-02-20 05:59:25,716: INFO] ZIM file created: wikipedia_my_all_nopic_2020-02.zim, 152.99 MiB
[2020-02-20 05:59:26,409: INFO] Starting uploader for /zim/wikipedia/wikipedia_my_all_nopic_2020-02.zim
[2020-02-20 05:59:49,427: INFO] Updating file-status=uploaded for wikipedia_my_all_nopic_2020-02.zim
[2020-02-20 06:25:19,422: ERROR] Unhandled exception: 404 Client Error: Not Found ("No such container: eb651b6d4375fd0b16ca0eef8fcb00d8078f51181de19d170a9fa319e905fee5")
[2020-02-20 06:25:19,423: ERROR] 404 Client Error: Not Found ("No such container: eb651b6d4375fd0b16ca0eef8fcb00d8078f51181de19d170a9fa319e905fee5")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/eb651b6d4375fd0b16ca0eef8fcb00d8078f51181de19d170a9fa319e905fee5/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/task-worker", line 60, in main
    sys.exit(worker.run())
  File "/usr/src/app/task/worker.py", line 458, in run
    self.upload_log()
  File "/usr/src/app/task/worker.py", line 387, in upload_log
    self.attempt_to_remove_log_container(filename)
  File "/usr/src/app/task/worker.py", line 342, in attempt_to_remove_log_container
    self.log_uploader.reload()
  File "/usr/local/lib/python3.8/site-packages/docker/models/resource.py", line 48, in reload
    new_model = self.collection.get(self.id)
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 880, in get
    resp = self.client.api.inspect_container(container_id)
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 757, in inspect_container
    return self._result(
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("No such container: eb651b6d4375fd0b16ca0eef8fcb00d8078f51181de19d170a9fa319e905fee5")
[2020-02-20 06:25:19,435: ERROR] exiting.
[2020-02-20 06:25:19,435: INFO] Trying to upload exception details
[2020-02-20 06:25:19,436: INFO] Shutting down task-worker
[2020-02-20 06:25:19,437: INFO] Stopping all containers and actions
[2020-02-20 06:25:19,437: INFO] Stopping and removing scraper
[2020-02-20 06:25:22,161: INFO] Stopping and removing DNS cache
[2020-02-20 06:25:23,793: INFO] Stopping and removing uploader
[2020-02-20 06:25:23,793: INFO] Removing task workdir /data
[2020-02-20 06:25:23,856: INFO] Updating task-status=failed
```
