### ISSUE TITLE
I don't get my worker working

### ISSUE THREAD

**Issue by JensKorte** [openzim/zimfarm#405]
[//]: # (Pick appropriate classifiers)
- Location: Worker
- Schedule Name/ID: __n/a__
- Task ID: __n/a__

## Problem

my worker doesn't work.  
```
zimfarm@devuan:~$ zimfarm start  
(re)starting zimfarm worker manager...  
:: stopping zimfarm_worker-manager  
[sudo] Passwort für zimfarm:  
zimfarm_worker-manager  
zimfarm_worker-manager  
:: starting zimfarm_worker-manager  
latest: Pulling from openzim/zimfarm-worker-manager
Digest: sha256:d45657b46777de81e92bb751559a6ed745dea3dc8524c6cf4910255e124d3ddd
Status: Image is up to date for openzim/zimfarm-worker-manager:latest
docker.io/openzim/zimfarm-worker-manager:latest
36053100b63d41ab17a1a7e0118adc251cca48a4d1965382ae22634fdf0f9976
```
And nothing ever happens and I wonder.
### zimfarm logs manage

```
[2020-02-16 11:47:03,050: INFO] starting zimfarm worker-manager.
[2020-02-16 11:47:03,050: INFO] configuration:
        username=hum
        webapi_uri=https://api.farm.openzim.org/v1
        socket_uri=tcp://tcp.farm.openzim.org:32029
        workdir=/data
        worker_name=hum
        poll_interval=180
        sleep_interval=5
        events=['requested-task', 'requested-tasks', 'cancel-task']
        selfish=False
        OFFLINERS=['mwoffliner', 'sotoki', 'gutenberg', 'phet']
[2020-02-16 11:47:03,051: INFO] testing workdir at /data…
[2020-02-16 11:47:03,051: INFO]         workdir is available and writable
[2020-02-16 11:47:03,051: INFO] testing private key at /etc/ssh/keys/zimfarm…
[2020-02-16 11:47:03,051: INFO]         private key is available and readable
[2020-02-16 11:47:03,051: INFO] testing authentication with https://api.farm.openzim.org/v1…
unable to load Private Key
140228656825472:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY
pkeyutl: Error initializing context
[2020-02-16 11:47:03,062: ERROR] authenticate() failure: unable to sign authentication payload
[2020-02-16 11:47:03,062: ERROR] unable to sign authentication payload
Traceback (most recent call last):
  File "/usr/src/app/common/worker.py", line 103, in authenticate
    self.access_token, self.refresh_token = get_token_ssh(
  File "/usr/src/app/common/dispatcher.py", line 48, in get_token_ssh
    raise IOError("unable to sign authentication payload")
OSError: unable to sign authentication payload
[2020-02-16 11:47:03,063: CRITICAL]     authentication failed.
```

### Steps where I am unsure
* Is my uploaded key right? Did I do a copy'n'paste mistake? Can I review it at the webinterface?
* my worker is configured selfish again. I tried non-selfish but it didn't change anything
* How do I request a test job for my worker?
* docker is new to me

## Reproducing steps

[//]: # (Information on how to reproduce it.)

**Comment by rgaudin** [comment]
Looks to me like you did not place the private key at the right place or it's not a proper one.

Could you please:

* share the output of `zimfarm config`
* Share the content of the file path mentioned in that previous command
* Share the result of `head -n 1 $ZIMFARM_ROOT/id_rsa` (replacing `$ZIMFARM_ROOT` with the actual ZIMFARM_ROOT from your config)
* Share the command you used to create your private and the platform you're running.

I'd advise you keep it selfif for now, as the logs says, it's an authentication problem so it just won't start requesting job until this is resolved.

Once you've been able to properly start the worker, @kelson42 will be able to request a `wikipedia_fr_test` run on your worker (it's a couple minutes task).

**Comment by JensKorte** [comment]
```
zimfarm@devuan:~$ zimfarm config
Using: /etc/zimfarm.config

Search paths:
  - /usr/local/bin/zimfarm.config
  - /spielerei/zimfarm/zimfarm/.zimfarm.config
  - /spielerei/zimfarm/zimfarm/zimfarm.config
  - /etc/zimfarm.config
```

```
zimfarm@devuan:~$ for f in /usr/local/bin/zimfarm.config /spielerei/zimfarm/zimfarm/.zimfarm.config /spielerei/zimfarm/zimfarm/zimfarm.config /etc/zimfarm.config;do echo "$f";ls -l "$f";done        
/usr/local/bin/zimfarm.config
ls: Zugriff auf '/usr/local/bin/zimfarm.config' nicht möglich: Datei oder Verzeichnis nicht gefunden
/spielerei/zimfarm/zimfarm/.zimfarm.config
ls: Zugriff auf '/spielerei/zimfarm/zimfarm/.zimfarm.config' nicht möglich: Datei oder Verzeichnis nicht gefunden
/spielerei/zimfarm/zimfarm/zimfarm.config
ls: Zugriff auf '/spielerei/zimfarm/zimfarm/zimfarm.config' nicht möglich: Datei oder Verzeichnis nicht gefunden
/etc/zimfarm.config
-rw-r--r-- 1 root root 1401 Feb 15 22:33 /etc/zimfarm.config
```

```
head -n 1 ~zimfarm/id_rsa
-----BEGIN OPENSSH PRIVATE KEY-----
```

ssh-keygen -t rsa -f id_rsa # I ran it as another user and changed the ownership of the file. That shouldn't matter imho

```
cat /etc/devuan_version
beowulf/ceres
cat /etc/apt/sources.list.d/docker.list
deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
```

**Comment by rgaudin** [comment]
Thank you @JensKorte, the problem is with your private key. README advises to create it with `ssh-keygen -t rsa -f id_rsa`, as you properly did, but it was implying the use of the PEM format which used to be default and is not nowadays.

Please, recreate your SSH keypair using `ssh-keygen -m PEM -t rsa -f id_rsa` and re-upload it.

**Comment by JensKorte** [comment]
The worker still doesn't work. What I did:
* rm -Rf id_rsa* # a dir wasn't removed by the first rm -Rf ???
* ssh-keygen -m PEM -t rsa -f id_rsa

```
curl -X POST https://api.farm.openzim.org/v1/users/hum/keys -H 'Authorization: Bearer <removed> -H 'Content-Type: application/json; charset=utf-8'  -d $'{"name": "another_name", "key": "}'
```

Maybe there is a problem with the key_name, maybe I used another name now and there is still the other key. When I tried to use the old name I get '{"error":"SSH key already exists"}'

Could the old key be removed, please.

**Comment by rgaudin** [comment]
![Screen Shot 2020-02-17 at 15 27 59](https://user-images.githubusercontent.com/57929/74666822-1e192800-519a-11ea-900c-fb9cf2394fe8.png)

the new key seems to have been uploaded. I'll remove the old one.

What do you mean by _The worker still doesn't work_ ? Can you please share the manager logs ?

**Comment by JensKorte** [comment]
> What do you mean by _The worker still doesn't work_ ? Can you please share the manager logs ?

I started the bug report when I had an error at the curl uploading command. Then I realized that a " was missing. Then I get

```
[2020-02-17 15:29:37,653: INFO] testing workdir at /data…
[2020-02-17 15:29:37,653: INFO]         workdir is available and writable
[2020-02-17 15:29:37,653: INFO] testing private key at /etc/ssh/keys/zimfarm…
[2020-02-17 15:29:37,653: INFO]         private key is available and readable
[2020-02-17 15:29:37,653: INFO] testing authentication with https://api.farm.openzim.org/v1…
[2020-02-17 15:29:37,905: ERROR] authenticate() failure: 401 Client Error: UNAUTHORIZED for url: https://api.farm.openzim.org/v1/auth/ssh_authorize
[2020-02-17 15:29:37,905: ERROR] 401 Client Error: UNAUTHORIZED for url: https://api.farm.openzim.org/v1/auth/ssh_authorize
Traceback (most recent call last):
  File "/usr/src/app/common/worker.py", line 103, in authenticate
    self.access_token, self.refresh_token = get_token_ssh(
  File "/usr/src/app/common/dispatcher.py", line 61, in get_token_ssh
    req.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://api.farm.openzim.org/v1/auth/ssh_authorize
[2020-02-17 15:29:37,907: CRITICAL]     authentication failed.
```

I thought the old key blocks the login. After a restart I still get
```
[2020-02-17 15:31:37,643: INFO] testing workdir at /data…
[2020-02-17 15:31:37,643: INFO]         workdir is available and writable
[2020-02-17 15:31:37,643: INFO] testing private key at /etc/ssh/keys/zimfarm…
[2020-02-17 15:31:37,643: INFO]         private key is available and readable
[2020-02-17 15:31:37,643: INFO] testing authentication with https://api.farm.openzim.org/v1…
[2020-02-17 15:31:37,976: ERROR] authenticate() failure: 401 Client Error: UNAUTHORIZED for url: https://api.farm.openzim.org/v1/auth/ssh_authorize
[2020-02-17 15:31:37,976: ERROR] 401 Client Error: UNAUTHORIZED for url: https://api.farm.openzim.org/v1/auth/ssh_authorize
Traceback (most recent call last):
  File "/usr/src/app/common/worker.py", line 103, in authenticate
    self.access_token, self.refresh_token = get_token_ssh(
  File "/usr/src/app/common/dispatcher.py", line 61, in get_token_ssh
    req.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://api.farm.openzim.org/v1/auth/ssh_authorize
[2020-02-17 15:31:37,992: CRITICAL]     authentication failed.
```

**Comment by JensKorte** [comment]
Works!

I made a mistake with the key.

**Comment by rgaudin** [comment]
Glad to hear ! 👍
