### ISSUE TITLE
authentication error after reboot

### ISSUE THREAD

**Issue by JensKorte** [openzim/zimfarm#412]
[//]: # (Pick appropriate classifiers)
- Location: Worker

## Problem

I had problems with the worker and Kelson told me to wait for the fix for too much jobs. I had to reboot my computer because of system updates. After the reboot I started with zimfarm start and got the error below.
The id_rsa seems to be in PEM format.

```
[2020-02-19 08:17:18,275: INFO] starting zimfarm worker-manager.
[2020-02-19 08:17:18,276: INFO] configuration:
        username=hum
        webapi_uri=https://api.farm.openzim.org/v1
        socket_uri=tcp://tcp.farm.openzim.org:32029
        workdir=/data
        worker_name=hum
        poll_interval=180
        sleep_interval=5
        events=['requested-task', 'requested-tasks', 'cancel-task']
        selfish=False
        OFFLINERS=['mwoffliner', 'sotoki', 'gutenberg', 'phet']
[2020-02-19 08:17:18,276: INFO] testing workdir at /data…
[2020-02-19 08:17:18,277: INFO]         workdir is available and writable
[2020-02-19 08:17:18,277: INFO] testing private key at /etc/ssh/keys/zimfarm…
[2020-02-19 08:17:18,277: INFO]         private key is available and readable
[2020-02-19 08:17:18,277: INFO] testing authentication with https://api.farm.openzim.org/v1…
[2020-02-19 08:17:18,455: ERROR] authenticate() failure: 401 Client Error: UNAUTHORIZED for url: https://api.farm.openzim.org/v1/auth/ssh_authorize
[2020-02-19 08:17:18,455: ERROR] 401 Client Error: UNAUTHORIZED for url: https://api.farm.openzim.org/v1/auth/ssh_authorize
Traceback (most recent call last):
  File "/usr/src/app/common/worker.py", line 103, in authenticate
    self.access_token, self.refresh_token = get_token_ssh(
  File "/usr/src/app/common/dispatcher.py", line 61, in get_token_ssh
    req.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://api.farm.openzim.org/v1/auth/ssh_authorize
[2020-02-19 08:17:18,457: CRITICAL]     authentication failed.
```

```

zimfarm@devuan:~$ ls -l
insgesamt 8
drwxr-xr-x 1 root    root      96 Feb 18 13:36 data
-rw------- 1 zimfarm zimfarm 1675 Feb 17 16:34 id_rsa
-rw-r--r-- 1 zimfarm zimfarm  396 Feb 17 16:34 id_rsa.pub
```

```
file *
data:       directory
id_rsa:     PEM RSA private key
id_rsa.pub: OpenSSH RSA public key
```

## Reproducing steps

[//]: # (Information on how to reproduce it.)

**Comment by rgaudin** [comment]
Thanks @JensKorte,
Given that it used to work, I'm a bit clueless. I've noticed that you uploaded a new `hum_zimfarm_pem2` key though… 
Maybe we could arrange a live chat so I could be looking at the server logs at the very moment you start your worker to see if there's an indication on the reason of the failure.

Potential reasons:

* Incorrect request. I think we can rule this out as you're using the current worker code.
* Datetime issue. Make sure your machine's date is configured and sync'ed properly
* Incorrect username. Shown in log, and is proper (`hum`).
* public key not properly uploaded
* Key being used not the one uploaded. Can you please send the output of `ssh-keygen -l -E md5 -f id_rsa` ?

**Comment by JensKorte** [comment]
>     * Datetime issue. Make sure your machine's date is configured and sync'ed properly

```
19 Feb 19:06:50 ntpdate[9207]: step time server 134.34.3.18 offset 84.823238 sec
```

Now it seems to work. Thank you!
