### ISSUE TITLE
docker socket read timeout

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#491]
We are now getting errors on docker API call (timeout reading the socket) at the very end of our task-worker.

Here's a full log of such a task:

```
[2020-06-03 17:46:49,978: INFO] Fetching task details for 5ed7e17e8ba4fa4207bf64f5
[2020-06-03 17:46:50,325: INFO] Updating task-status=started
[2020-06-03 17:46:50,769: INFO] Setting-up workdir
[2020-06-03 17:46:50,777: INFO] Starting DNS cache
[2020-06-03 17:46:51,517: DEBUG] DNS Cache started using IPs: ['172.17.0.4']
[2020-06-03 17:46:51,518: INFO] Starting scraper. Expects files at: /srv/zimfarm/data/5ed7e17e8ba4fa4207bf64f5
[2020-06-03 17:46:51,520: DEBUG] pulling image openzim/mwoffliner:1.10.8
[2020-06-03 17:46:52,116: INFO] Updating task-status=scraper_started
[2020-06-03 17:46:52,579: DEBUG] starting log uploader, with watch=True
[2020-06-04 04:32:47,405: INFO] ZIM file created: wikipedia_de_all_mini_2020-06.zim, 3.26 GiB
[2020-06-04 04:32:47,833: INFO] Starting uploader for /zim/wikipedia/wikipedia_de_all_mini_2020-06.zim
[2020-06-04 04:35:48,364: INFO] Updating file-status=uploaded for wikipedia_de_all_mini_2020-06.zim
[2020-06-05 08:06:07,232: INFO] ZIM file created: wikipedia_de_all_nopic_2020-06.zim, 11.94 GiB
[2020-06-05 08:06:08,166: INFO] Starting uploader for /zim/wikipedia/wikipedia_de_all_nopic_2020-06.zim
[2020-06-05 08:17:10,158: INFO] Updating file-status=uploaded for wikipedia_de_all_nopic_2020-06.zim
[2020-06-06 17:36:00,924: INFO] Updating task-status=scraper_completed. Exit code: 0
[2020-06-06 17:36:02,058: INFO] Waiting for scraper log to finish uploading
[2020-06-06 17:36:07,036: DEBUG] starting log uploader, with watch=False
[2020-06-06 17:36:11,702: INFO] Scraper log upload complete: 0
[2020-06-06 17:36:11,714: INFO] ZIM file created: wikipedia_de_all_maxi_2020-06.zim, 36.84 GiB
[2020-06-06 17:36:12,133: INFO] Starting uploader for /zim/wikipedia/wikipedia_de_all_maxi_2020-06.zim
[2020-06-06 18:09:20,745: INFO] Updating file-status=uploaded for wikipedia_de_all_maxi_2020-06.zim
[2020-06-06 18:09:21,196: INFO] Shutting down task-worker
[2020-06-06 18:09:21,196: INFO] Stopping all containers and actions
[2020-06-06 18:09:21,197: INFO] Stopping and removing scraper
[2020-06-06 18:12:21,307: ERROR] Unhandled exception: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=180)
[2020-06-06 18:12:21,307: ERROR] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=180)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=180)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/task-worker", line 60, in main
    sys.exit(worker.run())
  File "/usr/src/app/task/worker.py", line 485, in run
    self.shutdown("succeeded" if self.scraper_succeeded else "failed")
  File "/usr/src/app/task/worker.py", line 241, in shutdown
    self.stop()
  File "/usr/src/app/task/worker.py", line 227, in stop
    self.stop_scraper(timeout)
  File "/usr/src/app/task/worker.py", line 214, in stop_scraper
    self.scraper.remove()
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 347, in remove
    return self.client.api.remove_container(self.id, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 993, in remove_container
    res = self._delete(
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 238, in _delete
    return self.delete(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 615, in delete
    return self.request('DELETE', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=180)
[2020-06-06 18:12:21,421: ERROR] exiting.
[2020-06-06 18:12:21,421: INFO] Trying to upload exception details
[2020-06-06 18:12:21,422: INFO] Shutting down task-worker
[2020-06-06 18:12:21,422: INFO] Stopping all containers and actions
[2020-06-06 18:12:21,423: INFO] Stopping and removing scraper
[2020-06-06 18:12:21,429: ERROR] Could not submit failure details
```

* we're seing that mostly on protocol (EC2)
* we've seen it on mwoffliner1 at least once.
* mwoffliner1, 2, 3 have been upgraded recently:
  * they use same docker version as protocol (`19.03.x`)
  * they are on what looks like a similar architecture
* searches point to a docker-ec2 issue so it probably originates from a docker bug
* we're seeing it always at the same location, when *Stopping and removing scraper* so there's probably a link with what we do. We can probably avoid it.
* Our main issue is that we report task status after this clean-up phase so when it fails, the task is stalled to `scraper_completed`. At least, we should report that before (and let the prune clean the rest).

**Comment by kelson42** [comment]
New case? https://farm.openzim.org/pipeline/5edc8d27d0e51d7c7fc62127

**Comment by rgaudin** [comment]
> New case? https://farm.openzim.org/pipeline/5edc8d27d0e51d7c7fc62127

yes

**Comment by kelson42** [comment]
New case? https://farm.openzim.org/pipeline/5edb9498d0e51d7c7fc3862f

**Comment by rgaudin** [comment]
> New case? https://farm.openzim.org/pipeline/5edb9498d0e51d7c7fc3862f

Yes

**Comment by rgaudin** [comment]
Marking this as upstream as we've circumvented the effect of this and we suspect a docker bug.

**Comment by kelson42** [comment]
@rgaudin Thank you very much for the patch. I cross the fingers that it works. Do you have a link for the upstream bug? Does this make sense to keep this ticket open if we don't have an impact on our side (anymore)?

**Comment by rgaudin** [comment]
No need to cross fingers, we're just not looking at it anymore ; but it's still there so that's why I kept it open. We may want to check in the future whether this is fixed or not.

**Comment by rgaudin** [comment]
No activity since August, closing
