### ISSUE TITLE
Conflicting dnscache container name

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#568]
https://farm.openzim.org/pipeline/5fc662d486bd30ee81acfeed/debug

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.40/containers/create?name=5fc66_dnscache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/task-worker", line 60, in main
    sys.exit(worker.run())
  File "/usr/src/app/task/worker.py", line 448, in run
    self.start_dnscache()
  File "/usr/src/app/task/worker.py", line 195, in start_dnscache
    self.dnscache = start_dnscache(self.docker, self.task)
  File "/usr/src/app/common/docker.py", line 248, in start_dnscache
    return run_container(
  File "/usr/src/app/common/docker.py", line 84, in run_container
    return retried_docker_call(docker_client.containers.run, *args, **kwargs)
  File "/usr/src/app/common/docker.py", line 54, in retried_docker_call
    raise exc
  File "/usr/src/app/common/docker.py", line 43, in retried_docker_call
    return docker_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 809, in run
    container = self.create(image=image, command=command,
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 868, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 265, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/5fc66_dnscache" is already in use by container "ef4b0f73ca2b95dbfae3671af533425decc7cdd0265c917152dce9adc86905cc". You have to remove (or rename) that container to be able to reuse that name.")
```

**Comment by rgaudin** [comment]
Done
