### ISSUE TITLE
Tasks are reserved for many hours then get cancelled

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#571]
... then are rescheduled.

We have an extrem case with https://farm.openzim.org/recipes/wikipedia_en_medicine.

This is a new pattern I have observed many tomes these last weeks.

None of this should happen at all IMO.

**Comment by rgaudin** [comment]
That's quite weird. To get to such a situation, it means the manager receives the task (it is thus `reserved`) but the task-worker that gets fired immediately after fails to start properly (or fails to launch).
The canceling is normal if a task is reserved but not started after some time.
I've tried to reproduce the problem without success. [see this one](https://farm.openzim.org/pipeline/ce99623e44fa52c92e7bbcf5).
I'm leaving this open but I'm awaiting additional information. What would be best is being notified when this is hapening so I can look at the logs of the manager/task-worker.

**Comment by kelson42** [comment]
Other examples:
* https://farm.openzim.org/recipes/wikipedia_ar_medicine
* https://farm.openzim.org/recipes/wikipedia_vec_all
* https://farm.openzim.org/recipes/wikivoyage_ru

**Comment by rgaudin** [comment]
OK, this was due, as expected, to the task ID change. We are now creating containers with names such as `zimtask_xxxxx` while we were previously using `xxxxx_zimtask` (so it's easier to jump from one another).

Those failing ones are all trying to reach the new format but containers were created with old format.
For tasks started before the fix, this bug is to be expected. For those started recently, what happened is unclear as it's the same line of code being called for both actions (creating zimtask container and checking its log) and both are inside the manager, so in the same docker image…

restarted the workers. Seems to be working now. Fixed for all tasks `reserved` after now.

**Comment by rgaudin** [comment]
Eventually found the root cause of this. This is due to the pull-rate limit:

- worker receives a task
- worker informs API it is taking the task (`reserved`)
- worker tries to pull task-worker image
- fails to do so because of the limit
- after 30mn in `reserved`, period-tasks cancels it.

To me, this is the proper behavior and there's nothing to fix there. It does highlight the fact that we are still very much affected by pull-rate limits so I'm opening a new ticket to discuss how to address this.

```
2657 [2020-12-15 23:28:00,978: INFO] API is offering 1 task(s): ['a82a4aa7b4972a9a42049df5']
2658 [2020-12-15 23:28:00,979: DEBUG] start_task: a82a4aa7b4972a9a42049df5
2659 [2020-12-15 23:28:01,551: DEBUG] update_task_data: a82a4aa7b4972a9a42049df5
2660 [2020-12-15 23:28:01,889: DEBUG] start_task_worker: a82a4aa7b4972a9a42049df5
2661 [2020-12-15 23:28:01,894: DEBUG] getting image openzim/zimfarm-task-worker:latest
2662 [2020-12-15 23:28:01,982: DEBUG] Docker API Error for <bound method ImageCollection.pull of <docker.models.images.ImageCollection object at 0x7f34680614c0>> (attempt 1): 500 Server Error: Internal Server Error ("toomanyrequests: You have reached you     r pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2663 [2020-12-15 23:28:12,077: DEBUG] Docker API Error for <bound method ImageCollection.pull of <docker.models.images.ImageCollection object at 0x7f34680614c0>> (attempt 2): 500 Server Error: Internal Server Error ("toomanyrequests: You have reached you     r pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2664 [2020-12-15 23:28:32,157: DEBUG] Docker API Error for <bound method ImageCollection.pull of <docker.models.images.ImageCollection object at 0x7f34680614c0>> (attempt 3): 500 Server Error: Internal Server Error ("toomanyrequests: You have reached you     r pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2665 [2020-12-15 23:29:02,252: DEBUG] Docker API Error for <bound method ImageCollection.pull of <docker.models.images.ImageCollection object at 0x7f34680614c0>> (attempt 4): 500 Server Error: Internal Server Error ("toomanyrequests: You have reached you     r pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2666 [2020-12-15 23:29:42,350: DEBUG] Docker API Error for <bound method ImageCollection.pull of <docker.models.images.ImageCollection object at 0x7f34680614c0>> (attempt 5): 500 Server Error: Internal Server Error ("toomanyrequests: You have reached you     r pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2667 [2020-12-15 23:30:32,458: DEBUG] Docker API Error for <bound method ImageCollection.pull of <docker.models.images.ImageCollection object at 0x7f34680614c0>> (attempt 6): 500 Server Error: Internal Server Error ("toomanyrequests: You have reached you     r pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2668 [2020-12-15 23:31:32,648: DEBUG] Docker API Error for <bound method ImageCollection.pull of <docker.models.images.ImageCollection object at 0x7f34680614c0>> (attempt 7): 500 Server Error: Internal Server Error ("toomanyrequests: You have reached you     r pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2669 [2020-12-15 23:32:42,769: DEBUG] Docker API Error for <bound method ImageCollection.pull of <docker.models.images.ImageCollection object at 0x7f34680614c0>> (attempt 8): 500 Server Error: Internal Server Error ("toomanyrequests: You have reached you     r pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2670 [2020-12-15 23:34:02,904: DEBUG] Docker API Error for <bound method ImageCollection.pull of <docker.models.images.ImageCollection object at 0x7f34680614c0>> (attempt 9): 500 Server Error: Internal Server Error ("toomanyrequests: You have reached you     r pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2671 [2020-12-15 23:35:33,058: DEBUG] Docker API Error for <bound method ImageCollection.pull of <docker.models.images.ImageCollection object at 0x7f34680614c0>> (attempt 10): 500 Server Error: Internal Server Error ("toomanyrequests: You have reached yo     ur pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2672 [2020-12-15 23:37:13,221: ERROR] Unhandled exception: 500 Server Error: Internal Server Error ("toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-     limit")
2673 [2020-12-15 23:37:13,221: ERROR] 500 Server Error: Internal Server Error ("toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2674 Traceback (most recent call last):
2675   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 259, in _raise_for_status
2676     response.raise_for_status()
2677   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
2678     raise HTTPError(http_error_msg, response=self)
2679 requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.40/images/create?tag=latest&fromImage=openzim%2Fzimfarm-task-worker
2680
2681 During handling of the above exception, another exception occurred:
2682
2683 Traceback (most recent call last):
2684   File "/usr/local/bin/worker-manager", line 72, in main
2685     sys.exit(manager.run())
2686   File "/usr/src/app/manager/worker.py", line 334, in run
2687     self.poll()
2688   File "/usr/src/app/manager/worker.py", line 145, in poll
2689     self.start_task(response["items"].pop())
2690   File "/usr/src/app/manager/worker.py", line 261, in start_task
2691     self.start_task_worker(requested_task)
2692   File "/usr/src/app/manager/worker.py", line 270, in start_task_worker
2693     start_task_worker(
2694   File "/usr/src/app/common/docker.py", line 338, in start_task_worker
2695     docker_image = pull_image(docker_client, TASK_WORKER_IMAGE)
2696   File "/usr/src/app/common/docker.py", line 78, in pull_image
2697     return retried_docker_call(docker_client.images.pull, *args, **kwargs)
2698   File "/usr/src/app/common/docker.py", line 54, in retried_docker_call
2699     raise exc
2700   File "/usr/src/app/common/docker.py", line 43, in retried_docker_call
2701     return docker_method(*args, **kwargs)
2702   File "/usr/local/lib/python3.8/site-packages/docker/models/images.py", line 444, in pull
2703     pull_log = self.client.api.pull(
2704   File "/usr/local/lib/python3.8/site-packages/docker/api/image.py", line 415, in pull
2705     self._raise_for_status(response)
2706   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
2707     raise create_api_error_from_http_exception(e)
2708   File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
2709     raise cls(e, response=response, explanation=explanation)
2710 docker.errors.APIError: 500 Server Error: Internal Server Error ("toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")
2711 [2020-12-15 23:37:13,227: ERROR] exiting.
```
