### ISSUE TITLE
Unmatched quotes in config

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#714]
[youzimit task](https://farm.youzim.it/pipeline/b343e30ef13291d2c58f0236/debug) has a favicon param of:

```
https://gmka.org/wp-content/uploads/2021/08/doctor-630x760.png"
```

This crashes the task worker which is something we should avoid.

```
[2022-09-13 21:39:11,395: INFO] Fetching task details for b343e30ef13291d2c58f0236
[2022-09-13 21:39:11,484: INFO] Updating task-status=started
[2022-09-13 21:39:11,685: INFO] Setting-up workdir
[2022-09-13 21:39:11,701: INFO] Starting DNS cache
[2022-09-13 21:39:12,401: DEBUG] DNS Cache started using IPs: ['172.17.0.7']
[2022-09-13 21:39:12,401: INFO] Starting scraper. Expects files at: /data/zimfarm/data/b343e30ef13291d2c58f0236 
[2022-09-13 21:39:12,408: DEBUG] Pulling image ghcr.io/openzim/zimit:dev
[2022-09-13 21:39:12,979: ERROR] Unhandled exception: No closing quotation
[2022-09-13 21:39:12,979: ERROR] No closing quotation
Traceback (most recent call last):
  File "/usr/local/bin/task-worker", line 60, in main
    sys.exit(worker.run())
  File "/usr/src/app/task/worker.py", line 641, in run
    self.start_scraper()
  File "/usr/src/app/task/worker.py", line 306, in start_scraper
    self.scraper = start_scraper(
  File "/usr/src/app/common/docker.py", line 419, in start_scraper
    return run_container(
  File "/usr/src/app/common/docker.py", line 91, in run_container
    return retried_docker_call(docker_client.containers.run, *args, **kwargs)
  File "/usr/src/app/common/docker.py", line 49, in retried_docker_call
    return docker_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 819, in run
    container = self.create(image=image, command=command,
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 878, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 420, in create_container
    config = self.create_container_config(
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 431, in create_container_config
    return ContainerConfig(self._version, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/types/containers.py", line 701, in __init__
    command = split_command(command)
  File "/usr/local/lib/python3.8/site-packages/docker/utils/utils.py", line 464, in split_command
    return shlex.split(command)
  File "/usr/local/lib/python3.8/shlex.py", line 311, in split
    return list(lex)
  File "/usr/local/lib/python3.8/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/local/lib/python3.8/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/local/lib/python3.8/shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
[2022-09-13 21:39:12,987: ERROR] exiting.
[2022-09-13 21:39:12,987: INFO] Trying to upload exception details
[2022-09-13 21:39:12,988: INFO] Updating task-status=failed
```

**Comment by benoit74** [comment]
Duplicate of https://github.com/openzim/zimfarm/issues/668
