### ISSUE TITLE
Clarify whether name or title is too long

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#776]
I ran https://farm.openzim.org/pipeline/9bbb05499f337a426224b546/debug and got the error `{name}  is too long` but the log says `title is too long`

For sake of consistency I'd recommend sticking to one or the other, and adding the actual string for good measure.

Either way - and I'm not sure yet whether this should be a separate ticket but the name/title for [maitre_lucas_additions_20](https://farm.openzim.org/recipes/maitre_lucas_additions_20) is 25 characters long (and fails) whereas [maitre_lucas_alimentation](https://farm.openzim.org/recipes/maitre_lucas_alimentation) or [maitre_lucas_calcul_mental](https://farm.openzim.org/recipes/maitre_lucas_calcul_mental) succeeded and are 25 and 26 characters long, respectively.

**Comment by rgaudin** [comment]
You misread the log. 

```
[nautiluszim::2023-05-10 07:06:17,326] ERROR:Title is too long.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nautiluszim-1.1.1-py3.8.egg/nautiluszim/entrypoint.py", line 166, in main
    scraper.run()
  File "/usr/local/lib/python3.8/site-packages/nautiluszim-1.1.1-py3.8.egg/nautiluszim/scraper.py", line 180, in run
    self.zim_creator.start()
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 139, in start
    self.validate_metadata(name, value)
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 168, in validate_metadata
    validate_title(name, value)
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/metadata.py", line 44, in validate_title
    raise ValueError(f"{name} is too long.")
ValueError: Title is too long.
```

In this excerpt, the Human log feedback is the first line. The rest is the debug trace for developers. `f"{name} is too long."` is the code that produces `Title is too long`.

There is no discrepancy here. A single information is given: the `Title` metadata is too long.

The rest of your comment builds on the confusion between name and Title so I'll let you open another ticket if necessary (`Name` metadata has no limit)
