### ISSUE TITLE
HTTP 500 error linked to invalid ipv6 while removing secrets

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#954]
We've got a bunch of HTTP 500 errors on zimit farm with this kind of logs:

```
2024-04-27 01:09:55.308	ERROR:uwsgi_file__app_main:Exception on /v1/tasks/4c786084-4075-4a9d-9957-f1c3971fa40d [GET]
2024-04-27 01:09:55.308	Traceback (most recent call last):
2024-04-27 01:09:55.308	  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
2024-04-27 01:09:55.308	    response = self.full_dispatch_request()
2024-04-27 01:09:55.308	  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
2024-04-27 01:09:55.308	    rv = self.handle_user_exception(e)
2024-04-27 01:09:55.308	  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
2024-04-27 01:09:55.308	    return cors_after_request(app.make_response(f(*args, **kwargs)))
2024-04-27 01:09:55.308	  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
2024-04-27 01:09:55.308	    rv = self.dispatch_request()
2024-04-27 01:09:55.308	  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
2024-04-27 01:09:55.308	    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2024-04-27 01:09:55.308	  File "/app/./routes/base.py", line 20, in __call__
2024-04-27 01:09:55.308	    return handler(*args, **kwargs)
2024-04-27 01:09:55.308	  File "/app/./routes/__init__.py", line 70, in wrapper
2024-04-27 01:09:55.308	    return f(*args, **kwargs)
2024-04-27 01:09:55.308	  File "/app/./routes/__init__.py", line 87, in wrapper
2024-04-27 01:09:55.308	    return f(*args, **kwargs)
2024-04-27 01:09:55.308	  File "/app/./db/__init__.py", line 50, in inner
2024-04-27 01:09:55.308	    return func(*args, **kwargs)
2024-04-27 01:09:55.308	  File "/app/./routes/tasks/task.py", line 139, in get
2024-04-27 01:09:55.308	    remove_secrets_from_response(task)
2024-04-27 01:09:55.308	  File "/app/./routes/utils.py", line 29, in remove_secrets_from_response
2024-04-27 01:09:55.308	    remove_url_secrets(response)
2024-04-27 01:09:55.308	  File "/app/./routes/utils.py", line 101, in remove_url_secrets
2024-04-27 01:09:55.308	    remove_url_secrets(response[key])
2024-04-27 01:09:55.308	  File "/app/./routes/utils.py", line 106, in remove_url_secrets
2024-04-27 01:09:55.308	    urlparts = urlsplit(url)
2024-04-27 01:09:55.308	  File "/usr/local/lib/python3.8/urllib/parse.py", line 474, in urlsplit
2024-04-27 01:09:55.308	    raise ValueError("Invalid IPv6 URL")
2024-04-27 01:09:55.308	ValueError: Invalid IPv6 URL
2024-04-27 01:09:55.308	[pid: 25|app: 0|req: 46331/196535] 100.64.6.25 () {54 vars in 1481 bytes} [Fri Apr 26 23:09:55 2024] GET /v1/tasks/4c786084-4075-4a9d-9957-f1c3971fa40d => generated 265 bytes in 48 msecs (HTTP/1.1 500) 3 headers in 131 bytes (1 switches on core 0)
2024-04-27 01:09:55.308	100.64.6.25 - - [26/Apr/2024:23:09:55 +0000] "GET /v1/tasks/4c786084-4075-4a9d-9957-f1c3971fa40d HTTP/1.1" 500 265 "-" "python-requests/2.25.1" "100.64.6.1"
```

What is weird is that now it is no raising HTTP 500 anymore...

**Comment by elfkuzco** [comment]
@benoit74 , can you take a look at this? Seems to have been fixed as a consequence of the zimfarm-upgrade where we now use `show_secrets` while dumping model.

**Comment by benoit74** [comment]
I'm not sure it has been fixed, but it is so old and it was not yet even possible to reproduce at that time, so let's close it as "no-repro" for the time being.
